baseURL: "https://awaismustafa.com"
languageCode: en-us
title: Awais Mustafa
paginate: 5

theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false



minify:
  disableXML: true
  minifyOutput: true
 

    
    
menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 10

    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: Archieve
      name: Archive
      url: /archives
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60
    - dentifier: Blog
      name: Blog
      url: /blog
      weight: 20
    

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Awais Mustafa website, where Awais Mustafa features his projects, blogs, and awais mustafa thoughts. Follow Awais Mustafa website for more Updates. "
  keywords: [Awais Mustafa,awais mustafa,awaismustafa,Awais mustafa,awais Mustafa, Awais Mustafa,Awais mustafa,awais uom,awais Blog,Awais Mustafa Portfolio, Awais,Awais Mustafa blog,Awais Mustafa portfolio,awais,awais mustafa,awais blog,awais portfolio,Awwais,awwais,AwaisMustafa,awais devops,awais cloud,awais website,awwais.me, AI]

#   author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["/home/awaismustafa, awais-mustafa, awais mustafa, Awais Mustafa,awais mustafa,Awais Mustafa,awais mustafa website, Awais Mustafa Website, awais mustafa website, awais uom,awaistwt,awais mustafa linkedin,awais.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: false
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "awwais.me/favicon.ico"
    favicon16x16: "awwais.me/favicon-16x16.png"
    favicon32x32: "awwais.me/favicon-32x32.png"
    apple_touch_icon: "awwais.me/apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"


  label:
    text: "Awais Mustafa"
#     icon: /icon.svg
#     iconHeight: 35










  



  # Home Page
  profileMode:
    enabled: false
    title: "Devops, Cloud, and everything in between. "
    subtitle: "</>"
#    subtitle: "Hi 👋, I'm Awais, an [**BCS**](https://uom.edu.pk/) student at the **University of Malakand**. I'm passionate about **Backend**, **Cloud** and **DevOps**, and I'm also an Developer. Along with my undergrad studies, I've been working as a **DevOps Intern**. When I'm free, I write 😊 blogs on devOps, and make mini projects. I think that not scare you 👻"
#    imageUrl: "home/me.webp"
#    imageWidth: 220
#    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""
   
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Welcome to my website!, so Who am I?  I am a Passionate DevOps Engineer and Developer with a keen interest in DevSecOps, cloud computing, and programming.  I'm enthusiastic about command line tools and open-source software. so Sometimes I build stuff, sometimes I break stuff 👨‍🔧 [Read more](http://awaismustafa.com/about).  KeywordsForSeo: Awais Mustafa,Awais mustafa, Awais-Mustafa,awais mustafa,awais-mustafa.
    "


  






#     responsiveImages: false
#     linkFullImages: true
  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    hidden: true # hide everywhere but not in structured data

  socialIcons:

    - name: "email"
      url: /contact
    - name: "linkedin"
      url: "https://www.linkedin.com/in/awaais"
    - name: "github"
      url: "https://github.com/awwais"
    - name: "youtube"
      url: "https://www.youtube.com/"
    - name: "twitter"
      url: "https://twitter.com/awaistwt"
    - name: All my Links
      url: "http://awaismustafa.com/links"
      
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
#   analytics:
#     google:
#       SiteVerificationTag: "G-F4QF29BT8W"
#       google_site_verification: Ut7eBNONGLkuyT9d6V8omoShdrzoZRqhwz0MSMgZk8M 
#     bing:
#       SiteVerificationTag: "XYZabc"
#     yandex:
#       SiteVerificationTag: "XYZabc"
# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
      
      
      
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai










    
    
    
    
    
    

    
    
      
      
